"""Remove FK from note_history

Revision ID: 6abee110e0ef
Revises: 5d813aa327f8
Create Date: 2025-10-24 20:46:07.622485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '6abee110e0ef'
down_revision = '5d813aa327f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind() 

    op.create_table('note_history_temp',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('note_id', sa.String(length=36), nullable=False),  # ← Just a string now, not FK!
        sa.Column('user_id', sa.String(length=36), nullable=False),  # ← NEW column
        sa.Column('title', sa.String(length=45), nullable=False),
        sa.Column('action', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),  # ← FK to users only
        sa.PrimaryKeyConstraint('id')
    )

    conn.execute(text("""
        INSERT INTO note_history_temp (id, note_id, user_id, title, action, created_at)
        SELECT 
            nh.id,
            nh.note_id,
            COALESCE(n.owner_id, 
                     (SELECT user_id FROM users ORDER BY created_at ASC LIMIT 1)) as user_id,
            nh.title,
            nh.action,
            nh.created_at
        FROM note_history nh
        LEFT JOIN notes n ON n.id = nh.note_id
    """))

    # Drop old table
    op.drop_table('note_history')
    
    # Rename temp table
    op.rename_table('note_history_temp', 'note_history')

    # ### end Alembic commands ###


def downgrade():
    conn = op.get_bind()
    
    op.create_table('note_history_temp',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('note_id', sa.String(length=36), nullable=False),
        sa.Column('title', sa.String(length=45), nullable=False),
        sa.Column('action', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    conn.execute(text("""
        INSERT INTO note_history_temp (id, note_id, title, action, created_at)
        SELECT nh.id, nh.note_id, nh.title, nh.action, nh.created_at
        FROM note_history nh
        INNER JOIN notes n ON n.id = nh.note_id
    """))
    
    op.drop_table('note_history')
    op.rename_table('note_history_temp', 'note_history')
